#!/usr/bin/env bash
if ! [ -f ./remote-location ]; then
    echo "./remote-location does not exist. Please create it and put an IP address in it."
    exit 1
fi

ssh root@$(cat ./remote-location) -i vultr2