#!/bin/bash
rm static/downloads/*
ln landing.html static/downloads
ln snippets/* static/downloads
cp main.py static/downloads
chmod -x static/downloads/main.py
ln static/javascript/main.ts static/downloads
ln static/styles/stylesheet.css static/downloads
