#!/bin/bash
echo "Symlinking ./nginx to relevant directories..."
if [ -f /etc/nginx/sites-available/resume-webpage ]; then
  sudo rm /etc/nginx/sites-available/resume-webpage
fi
if [ -f /etc/nginx/sites-enabled/resume-webpage ]; then
  sudo rm /etc/nginx/sites-enabled/resume-webpage
fi
sudo ln -s "$PWD"/nginx /etc/nginx/sites-available/resume-webpage
sudo ln -s "$PWD"/nginx /etc/nginx/sites-enabled/resume-webpage
echo "Running 'systemctl restart nginx'..."
sudo systemctl restart nginx
echo "All done."