#!/bin/bash
mkdir -p static/downloads
rm static/downloads/* > /dev/null 2>&1
ln landing.html static/downloads
ln snippets/* static/downloads
cp main.py static/downloads
chmod -x static/downloads/main.py
ln static/javascript/main.ts static/downloads
ln static/styles/stylesheet.css static/downloads
