#!/bin/bash
echo "Symlinking ./nginx to relevant directories..."
sudo rm /etc/nginx/sites-available/portfolio-webpage > /dev/null 2>&1
sudo rm /etc/nginx/sites-enabled/portfolio-webpage > /dev/null 2>&1
sudo ln -s "$PWD"/nginx /etc/nginx/sites-available/portfolio-webpage
sudo ln -s "$PWD"/nginx /etc/nginx/sites-enabled/portfolio-webpage
echo "Running 'systemctl restart nginx'..."
sudo systemctl restart nginx
echo "All done."