#!/usr/bin/env bash

echo "Running autopep8..."
autopep8 --in-place --max-line-length 90 ./*.py update-webpage tsdaemon trivial-hit-counter
echo "Running isort..."
isort ./*.py update-webpage tsdaemon trivial-hit-counter
echo "Running interrogate *.py"
interrogate ./*.py
