#!/bin/bash
if [ "$(basename "$PWD")" != "portfolio-webpage" ]; then
   echo "Wrong directory; Please cd to your nearest portfolio-webpage."
   exit 0
fi
git fetch
git reset --hard origin/master
/usr/bin/env python3 work.py
echo "Running 'sudo systemctl daemon-reload'. You may be asked for your password."
sudo systemctl daemon-reload
echo "Running 'sudo systemctl restart portfolio-webpage'"
sudo systemctl restart portfolio-webpage
echo "All done."